import Link from "next/link";
import "../styles/globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const hearder = (
    <header>
      <div className="text-center">
        <Link href="/">
          <h1 className="text-3xl text-pink-500">Yan's Code Blog</h1>
        </Link>
        <p>🍓Welcome to my tech blog.💻</p>
        <br />
      </div>
    </header>
  );
  const footer = (
    <footer>
      <div>
        <br />
        <h3>Developed by Yan</h3>
      </div>
    </footer>
  );

  return (
    <html lang="en">
      <head />
      <body>
        <div className="mx-auto  max-w-2xl">
          {hearder}
          {children}
          {footer}
        </div>
      </body>
    </html>
  );
}
