import '../styles/globals.css';

import { FaGithub, FaGlobe, FaLinkedin, FaTwitter } from 'react-icons/fa';

import Link from 'next/link';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const hearder = (
    <header>
      <div className='text-center bg-slate-800 p-8 my-6 rounded-md'>
        <Link href='/'>
          <h1 className='text-2xl text-pink-300 mb-3 font-bold'>
            Yan's Code Blog
          </h1>
        </Link>
        <p className=' text-pink-300'>🍓 Welcome to my tech blog. ☕</p>
      </div>
    </header>
  );
  const footer = (
    <>
      <div className='border-t border-slate-400 mt-12 text-center text-slate-400'></div>
      <div className='p-5 text-center '>
        <ul>
          <div className='flex justify-between'>
            <div></div>
            <p className=' text-slate-700 font-bold text-xl pb-6 '>
              Contact <span className='text-pink-600'> Me</span>{' '}
            </p>
            <a href='https://visitorbadge.io/status?path=https%3A%2F%2Fwww.yancodeblog.codes%2F'>
              <img src='https://api.visitorbadge.io/api/visitors?path=https%3A%2F%2Fwww.yancodeblog.codes%2F&labelColor=%23f47373&countColor=%2337d67a' />
            </a>
          </div>

          <div className='flex justify-between gap-6 pb-5'>
            <a href='https://github.com/yanliu1111' title='Github'>
              <FaGithub className='text-xl cursor-pointer hover:text-red-600' />
            </a>
            <a
              href='https://www.linkedin.com/in/yan-liu-phd-371b8562/'
              title='LinkedIn'
            >
              <FaLinkedin className='text-xl cursor-pointer hover:text-blue-600' />
            </a>

            <a href='https://twitter.com/yanliu111' title='Twitter'>
              <FaTwitter className='text-xl cursor-pointer hover:text-yellow-600' />
            </a>
          </div>
        </ul>
      </div>
    </>
  );

  return (
    <html lang='en'>
      <head />
      <body>
        <div className='mx-auto max-w-6xl px-6'>
          {hearder}
          {children}
          {footer}
        </div>
      </body>
    </html>
  );
}
